"""EGAKU AI - Legal compliance, content policy, and age verification."""

# ──────────────────────────────────────────────
# Content Policy / コンテンツポリシー
# ──────────────────────────────────────────────

CONTENT_POLICY = {
    "en": """
## Content Policy

### Permitted Content
- General artwork and illustrations (SFW)
- Adult/NSFW content depicting **fictional characters** aged 18+
- Artistic nude and erotic content between consenting adult characters
- Fantasy, horror, and other creative expressions protected under freedom of expression

### Strictly Prohibited Content
The following content is **illegal** and strictly prohibited under international law:
- **Child Sexual Abuse Material (CSAM)** — Any sexual depiction of minors or characters appearing to be minors
- **Non-consensual content** — Deepfakes or realistic depictions of real persons without their consent
- **Content that violates local laws** — Users must comply with all applicable laws in their jurisdiction
- **Content promoting violence against real individuals**
- **Content involving real minors in any context**

### Enforcement
- Violation of prohibited content rules will result in immediate account termination
- Illegal content will be reported to relevant authorities
- AI-generated content must not be used to harass, defame, or harm real individuals

### User Responsibility
Users are solely responsible for ensuring their generated content complies with all applicable laws in their jurisdiction.
""",
    "ja": """
## コンテンツポリシー

### 許可されるコンテンツ
- 一般的なアートワーク・イラスト（SFW）
- **18歳以上の架空のキャラクター**を描いたアダルト/NSFWコンテンツ
- 合意のある成人キャラクター間の芸術的ヌード・エロティックコンテンツ
- ファンタジー、ホラー、その他表現の自由のもとで保護される創作表現

### 厳禁コンテンツ（違法）
以下のコンテンツは国際法のもと**違法**であり、厳禁です：
- **児童性的虐待素材（CSAM）** — 未成年者または未成年に見えるキャラクターのいかなる性的描写
- **非同意コンテンツ** — 実在の人物の同意なきディープフェイクまたはリアルな描写
- **各国法律に違反するコンテンツ** — ユーザーは居住地の全ての適用法を遵守する必要があります
- **実在の個人に対する暴力を助長するコンテンツ**
- **実在の未成年者をいかなる文脈で含むコンテンツ**

### 執行
- 禁止コンテンツに違反した場合、アカウントは即時停止されます
- 違法コンテンツは関連当局に報告されます
- AI生成コンテンツを実在の個人への嫌がらせ、名誉毀損、危害に使用してはなりません

### ユーザーの責任
ユーザーは、生成したコンテンツが居住地域の全ての適用法に準拠していることを確認する全責任を負います。
""",
}

# ──────────────────────────────────────────────
# Terms of Service (Summary)
# ──────────────────────────────────────────────

TERMS_OF_SERVICE = {
    "en": """
## Terms of Service (Summary)

1. **Age Requirement**: You must be 18 years or older to use adult content features.
2. **Content Ownership**: You retain rights to content you generate, subject to the underlying model licenses.
3. **Prohibited Use**: See Content Policy above. Violations result in termination.
4. **No Warranty**: The service is provided "as is" without warranty of any kind.
5. **Liability**: The platform is not liable for content generated by users.
6. **Self-Hosted Disclaimer**: If you run this software on your own hardware, you assume full legal responsibility for all content generated.
""",
    "ja": """
## 利用規約（要約）

1. **年齢要件**: アダルトコンテンツ機能を使用するには18歳以上である必要があります。
2. **コンテンツの所有権**: 生成したコンテンツの権利はユーザーに帰属します（基盤モデルのライセンスに従います）。
3. **禁止使用**: 上記コンテンツポリシーを参照。違反はアカウント停止となります。
4. **保証なし**: 本サービスは「現状のまま」提供され、いかなる保証もありません。
5. **責任**: プラットフォームはユーザーが生成したコンテンツに対して責任を負いません。
6. **セルフホスト免責**: 本ソフトウェアを自身のハードウェアで実行する場合、生成された全てのコンテンツに対する法的責任はユーザーが全て負います。
""",
}

# ──────────────────────────────────────────────
# Self-hosted Warning / セルフホスト警告
# ──────────────────────────────────────────────

SELF_HOSTED_WARNING = {
    "en": """
⚠️ **SELF-HOSTED SOFTWARE DISCLAIMER**

This software is provided as open-source for personal and commercial use.
When running on your own hardware:

- **YOU are solely responsible** for all content generated using this software.
- You must comply with **all applicable laws** in your country/region.
- Adult (NSFW) content generation is permitted for **legal content only**.
- **Illegal content (CSAM, non-consensual deepfakes, etc.) is strictly prohibited** regardless of jurisdiction.
- The developers of this software bear **no liability** for user-generated content.

By proceeding, you confirm that you are **18 years or older** and agree to use this software in compliance with all applicable laws.
""",
    "ja": """
⚠️ **セルフホストソフトウェア免責事項**

本ソフトウェアはオープンソースとして個人・商用利用のために提供されています。
自身のハードウェアで実行する場合：

- 本ソフトウェアを使用して生成された全てのコンテンツについて、**ユーザーが全責任を負います**。
- お住まいの国/地域の**全ての適用法**を遵守する必要があります。
- アダルト（NSFW）コンテンツの生成は**合法なコンテンツに限り**許可されます。
- **違法コンテンツ（CSAM、非同意ディープフェイク等）は管轄地域に関わらず厳禁**です。
- 本ソフトウェアの開発者はユーザー生成コンテンツに対して**一切の責任を負いません**。

続行することで、**18歳以上**であること、および全ての適用法に準拠して本ソフトウェアを使用することに同意したものとみなされます。
""",
}

# ──────────────────────────────────────────────
# Age Verification Dialog
# ──────────────────────────────────────────────

AGE_VERIFICATION = {
    "en": {
        "title": "Age Verification Required",
        "message": "This application contains features for generating adult (NSFW) content. You must be 18 years or older to access these features.",
        "confirm": "I confirm that I am 18 years or older",
        "deny": "I am under 18 (exit adult features)",
    },
    "ja": {
        "title": "年齢確認が必要です",
        "message": "このアプリケーションにはアダルト（NSFW）コンテンツを生成する機能が含まれています。これらの機能にアクセスするには18歳以上である必要があります。",
        "confirm": "18歳以上であることを確認します",
        "deny": "18歳未満です（アダルト機能を終了）",
    },
}

# ──────────────────────────────────────────────
# Regional Content Guidelines / 地域別コンテンツガイドライン
# ──────────────────────────────────────────────

REGIONAL_GUIDELINES = {
    "en": """
## Regional Content Guidelines

EGAKU AI follows the laws of each user's country/region. Adult content rules vary by jurisdiction.

### How It Works
- Your region is **automatically detected** via IP address.
- Content rules are applied based on your detected region.
- **You cannot manually change your region** to bypass local laws.

### Region-Specific Rules

| Region | Genital Exposure | Mosaic Required | Notes |
|--------|-----------------|-----------------|-------|
| **Japan (JP)** | Allowed | **Yes (auto-applied)** | Article 175 of the Penal Code requires obscuring of genitalia |
| **United States (US)** | Allowed | No | Legal for fictional adult content. User's responsibility. |
| **United Kingdom (UK)** | Allowed | No | Must comply with Online Safety Act |
| **Germany (DE)** | Allowed | No | Strict age verification required |
| **South Korea (KR)** | Restricted | **Yes** | Stricter obscenity laws apply |
| **Australia (AU)** | Allowed | No | Must comply with Classification Act |
| **Other regions** | Allowed | No | User assumes responsibility per local laws |

### Universal Rules (All Regions)
- **CSAM is illegal everywhere** — zero tolerance, reported to authorities
- **Non-consensual deepfakes are illegal** — real persons require consent
- **Age verification (18+)** is required for all NSFW content
- **You are responsible** for ensuring compliance with your local laws

### NSFW Blur Feature
- All NSFW content is **blurred by default** in galleries and thumbnails
- Verified 18+ users can toggle blur off in their settings
- Shared links always show blurred versions unless the viewer is verified 18+

### Self-Hosted Users
If you run EGAKU AI on your own hardware:
- All regional rules above are **your personal responsibility**
- The software provides tools (mosaic filter, content policy check) but **enforcement is on you**
- The developers bear no liability for content generated on self-hosted instances
""",
    "ja": """
## 地域別コンテンツガイドライン

EGAKU AI はユーザーの国/地域の法律に従います。アダルトコンテンツのルールは管轄地域により異なります。

### 仕組み
- お住まいの地域は **IPアドレスから自動検出** されます。
- 検出された地域に基づきコンテンツルールが適用されます。
- 現地の法律を回避するために **手動で地域を変更することはできません**。

### 地域別ルール

| 地域 | 性器表現 | モザイク | 備考 |
|------|---------|---------|------|
| **日本 (JP)** | 可 | **必須（自動適用）** | 刑法175条によりわいせつ物の頒布にはモザイク処理が必要 |
| **アメリカ (US)** | 可 | 不要 | 架空の成人コンテンツは合法。自己責任。 |
| **イギリス (UK)** | 可 | 不要 | Online Safety Act に準拠必須 |
| **ドイツ (DE)** | 可 | 不要 | 厳格な年齢確認が必要 |
| **韓国 (KR)** | 制限あり | **必須** | より厳格なわいせつ法が適用 |
| **オーストラリア (AU)** | 可 | 不要 | Classification Act に準拠必須 |
| **その他の地域** | 可 | 不要 | 現地の法律に基づきユーザーが責任を負う |

### 全地域共通ルール
- **CSAMは全世界で違法** — 一切容認せず、当局に報告
- **非同意ディープフェイクは違法** — 実在の人物は本人の同意が必要
- **年齢確認（18歳以上）** は全てのNSFWコンテンツに必要
- 現地の法律の遵守は **ユーザーの責任** です

### NSFWブラー機能
- NSFWコンテンツはギャラリー・サムネイルで **デフォルトでブラー表示**
- 18歳以上確認済みユーザーは設定でブラーをオフにできます
- 共有リンクでは、閲覧者が18歳以上確認済みでない限りブラー表示を維持

### セルフホストユーザー
EGAKU AI を自身のハードウェアで実行する場合：
- 上記の全ての地域別ルールは **個人の責任** です
- ソフトウェアはツール（モザイクフィルター、コンテンツポリシーチェック）を提供しますが、**執行はユーザーの責任** です
- セルフホストインスタンスで生成されたコンテンツに対して開発者は一切の責任を負いません
""",
}

# ──────────────────────────────────────────────
# Region rules configuration
# ──────────────────────────────────────────────

REGION_RULES = {
    "JP": {"genital_mosaic_required": True, "age_verification": "strict"},
    "KR": {"genital_mosaic_required": True, "age_verification": "strict"},
    "DE": {"genital_mosaic_required": False, "age_verification": "strict"},
    "AU": {"genital_mosaic_required": False, "age_verification": "standard"},
    "US": {"genital_mosaic_required": False, "age_verification": "standard"},
    "GB": {"genital_mosaic_required": False, "age_verification": "standard"},
    "DEFAULT": {"genital_mosaic_required": False, "age_verification": "standard"},
}


def get_region_rules(country_code):
    """Get content rules for a given country code."""
    return REGION_RULES.get(country_code, REGION_RULES["DEFAULT"])


# ──────────────────────────────────────────────
# Prohibited content detection keywords
# (Basic filter - not exhaustive, for flagging purposes)
# ──────────────────────────────────────────────

PROHIBITED_KEYWORDS = [
    "child", "children", "kid", "kids", "minor", "minors",
    "underage", "loli", "lolita", "shota", "shotacon",
    "preteen", "toddler", "infant", "baby",
    "young girl", "young boy", "little girl", "little boy",
    "elementary school", "middle school",
    "小学生", "中学生", "幼女", "幼児", "ロリ", "ショタ",
    "児童", "未成年",
]


def check_prompt_compliance(prompt):
    """Check if a prompt contains prohibited content keywords.
    Returns (is_safe, flagged_terms).
    """
    prompt_lower = prompt.lower()
    flagged = []
    for kw in PROHIBITED_KEYWORDS:
        if kw.lower() in prompt_lower:
            flagged.append(kw)
    return len(flagged) == 0, flagged


def get_violation_message(flagged_terms, lang="en"):
    """Return violation message for flagged content."""
    if lang == "ja":
        return (
            f"⛔ コンテンツポリシー違反: 以下の禁止キーワードが検出されました: {', '.join(flagged_terms)}\n\n"
            "未成年者を含む、または暗示するコンテンツの生成は固く禁じられています。\n"
            "これは法律違反であり、当局に報告される場合があります。"
        )
    return (
        f"⛔ Content Policy Violation: Prohibited keywords detected: {', '.join(flagged_terms)}\n\n"
        "Generation of content depicting or implying minors is strictly prohibited.\n"
        "This is illegal and may be reported to authorities."
    )
